services:
  filebrowser:

    # Imagem
    image: filebrowser/filebrowser:v2.63.23

    # Identificação
    container_name: filebrowser
    hostname: filebrowser

    # Reinício
    restart: unless-stopped

    # Segurança
    security_opt:
      - no-new-privileges:true

    # Ambiente
    env_file:
      - .env

    environment:
      - TZ=${TZ}

    # Portas
    ports:
      - "${FILEBROWSER_PORT}:80"

    # Volumes
    volumes:
      - /srv/storage:/srv
      - /srv/services/filebrowser/database:/database
      - /srv/services/filebrowser/config:/config

    # Rede
    networks:
      - homeserver

networks:
  homeserver:
    external: true