services:
  caddy:
    image: caddy:2

    container_name: caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      - LAN_IP=${HS_HOST_IP:-192.168.0.10}

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/config/tls:/etc/tls:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - homeserver

volumes:
  caddy_data:
  caddy_config:

networks:
  homeserver:
    external: true