services:
  gitea:

    # Imagem
    image: gitea/gitea:1.27.0

    # Identificação
    container_name: gitea
    hostname: gitea

    # Reinício
    restart: unless-stopped

    # Segurança
    security_opt:
      - no-new-privileges:true

    # Variáveis
    env_file:
      - .env

    environment:
      TZ: ${TZ}
      USER_UID: ${PUID}
      USER_GID: ${PGID}

    # Portas
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"

    # Dados
    volumes:
      - /srv/services/gitea:/data

    # Rede
    networks:
      - homeserver

networks:
  homeserver:
    external: true