profiles:

  minimal:

    services:

      - homepage

      - filebrowser

  default:

    services:

      - homepage

      - gitea

      - filebrowser

      - portainer

  media:

    services:

      - homepage

      - jellyfin

      - immich

  developer:

    services:

      - homepage

      - gitea

      - portainer

  complete:

    services:

      - homepage

      - gitea

      - filebrowser

      - portainer

      - immich

      - jellyfin