schema:
  version: "1.0"

platform:
  id: homeserver

  name: HomeServer

  edition: community

  version: "1.0.0"

  description: >
    Plataforma para provisionamento e gerenciamento de serviços
    domésticos utilizando Docker.

workspace:
  root: /srv

repository:
  name: homeserver-config

compose:
  filename: compose.yaml

metadata:
  filename: metadata.yaml

environment:
  filename: .env