services:
  portainer:
    image: portainer/portainer-ce:lts

    container_name: portainer

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    ports:
      - "${PORTAINER_PORT}:9443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/docker/volumes/portainer:/data

    environment:
      - TZ=${TZ}

    networks:
      - homeserver

networks:
  homeserver:
    external: true
