services:
  <service-name>:

    # =====================================================
    # Imagem
    # =====================================================

    image:

    # =====================================================
    # Identificação
    # =====================================================

    container_name:
    hostname:

    # =====================================================
    # Reinício
    # =====================================================

    restart: unless-stopped

    # =====================================================
    # Segurança
    # =====================================================

    security_opt:
      - no-new-privileges:true

    # =====================================================
    # Variáveis
    # =====================================================

    env_file:
      - .env

    environment:

    # =====================================================
    # Portas
    # =====================================================

    ports:

    # =====================================================
    # Volumes
    # =====================================================

    volumes:

    # =====================================================
    # Redes
    # =====================================================

    networks:
      - homeserver

    # =====================================================
    # Logs
    # =====================================================

    logging: