---
- Links:

    - Desenvolvimento:
        - GitHub:
            - abbr: GH
              href: https://github.com/

        - Gitea:
            - abbr: GT
              href: http://192.168.1.10:3001

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

        - YouTube:
            - abbr: YT
              href: https://youtube.com/

    - Servidor:
        - Homepage:
            - abbr: HP
              href: http://192.168.1.10:3000

        - FileBrowser:
            - abbr: FB
              href: http://192.168.1.10:8080
