title: HomeServer
description: Hub central do servidor doméstico
language: pt-BR

theme: dark
color: slate

target: _blank
headerStyle: boxed
fullWidth: true
statusStyle: dot
showStats: true
useEqualHeights: true

hideVersion: true
disableUpdateCheck: true
disableIndexing: true
hideErrors: true

quicklaunch:
  searchDescriptions: true
  hideVisitURL: true
  provider: duckduckgo

layout:
  Meu espaço:
    style: row
    columns: 4
  Aplicações:
    style: row
    columns: 4
  Administração:
    style: row
    columns: 4
  Sistema:
    style: row
    columns: 4
