---
- greeting:
    text_size: sm
    text: HomeServer

- resources:
    cpu: true
    memory: true
    disk: /host

- datetime:
    locale: pt-BR
    format:
      dateStyle: short
      timeStyle: short
