services:
  api:
    build: .

    working_dir: /workspace/api

    volumes:
      - ..:/workspace
      - /workspace/api/node_modules
      - /etc/hostname:/etc/hostname:ro
      - /etc/os-release:/etc/os-release:ro

    command: npm run dev

    ports:
      - "8000:8000"
