services:
  api:
    build: .
    working_dir: /workspace/api
    env_file:
      - .env
    environment:
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_ed25519 -o User=git -o StrictHostKeyChecking=accept-new
    cap_add:
      - SYS_RAWIO
    volumes:
      - ..:/workspace
      - /workspace/api/node_modules
      - /etc/hostname:/etc/hostname:ro
      - /etc/os-release:/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
      - /srv/storage:/srv/storage:ro
      - /srv/backup:/srv/backup:ro
      - //home/usuario/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    restart: unless-stopped
    command: npm run dev
    ports:
      - "8000:8000"
    networks:
      - homeserver

networks:
  homeserver:
    external: true
