directories:

  git:
    path: git

  docker:
    path: docker

  docker_compose:

  path: docker/compose

  create: true

  permissions: default

  owner: homeserver

  docker_configs:
    path: docker/configs

  docker_networks:
    path: docker/networks

  docker_secrets:
    path: docker/secrets

  docker_stacks:
    path: docker/stacks

  docker_volumes:
    path: docker/volumes

  data:
    path: data

  backup:
    path: backup

  logs:
    path: logs

  runtime:
    path: runtime

  scripts:
    path: scripts