docker:

  compose:

    directory: docker/compose

    filename: compose.yaml

  configs:

    directory: docker/configs

  secrets:

    directory: docker/secrets

  volumes:

    directory: docker/volumes

  networks:

    directory: docker/networks

  stacks:

    directory: docker/stacks